### ISSUE TITLE
App does not work when built and hosted as a static site

### ISSUE THREAD

**Issue by jakubgs** [status-im/gnosis-safe-waku#1]
I tried building this project with `yarn build`, which worked:
```
 > yarn build
yarn run v1.22.17
$ yarn workspace @scaffold-eth/react-app build --max-old-space-size=12288
warning package.json: No license field
$ react-scripts build --max-old-space-size=12288
Creating an optimized production build...
...
File sizes after gzip:

  1.89 MB (+12 B)   build/static/js/2.0847626c.chunk.js
  68.52 KB          build/static/css/2.ebe1976d.chunk.css
  17.07 KB (-59 B)  build/static/js/main.57e31647.chunk.js
  1.19 KB           build/static/js/runtime-main.0b7ec1b4.js
  700 B (+2 B)      build/static/js/3.62f836df.chunk.js
  669 B (+1 B)      build/static/js/4.01aedefc.chunk.js
  167 B             build/static/css/main.a03291b5.chunk.css

Done in 89.64s.
```
But when I try to host the built site:
```
 > cd packages/react-app/build 
 > python -m http.server 8888
Serving HTTP on 0.0.0.0 port 8888 (http://0.0.0.0:8888/) ...
```
It fails at load time in the browser with:
```
index.js:7 Uncaught TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at Module.<anonymous> (index.js:7:21)
    at u ((index):1:1297)
    at Object.<anonymous> (ed25519.js:3:12)
    at u ((index):1:1297)
    at Object.<anonymous> (ed25519-class.js:8:16)
    at u ((index):1:1297)
    at Object.<anonymous> (index.js:14:12)
    at u ((index):1:1297)
    at Object.<anonymous> (index.js:5:14)
```

**Comment by jakubgs** [comment]
The error appears to be triggered in this line:
```js
const CURVE_ORDER = _2n ** BigInt(252) + BigInt('27742317777372353535851937790883648493');
```
Which is from the `noble-ed25519` package, which does have an issue open with the same error:

* https://github.com/paulmillr/noble-ed25519/issues/23

Apparently [the solution](https://github.com/0xs34n/starknet.js/issues/37#issuecomment-955797303) is to add this config to `package.json`:
```
  "browserslist": {
    "production": [
      "chrome >= 67",
      "edge >= 79",
      "firefox >= 68",
      "opera >= 54",
      "safari >= 14"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

**Comment by jakubgs** [comment]
Okay, after clearing `node_modules` and reinstalling and rebuilding everything I now get a different error:
```
crypto.ts:22 Uncaught Error: crypto and/or subtle api unavailable
    at Object.<anonymous> (crypto.ts:22:9)
    at u ((index):1:1297)
    at Object.<anonymous> (GnosisStarterView.jsx:1:1)
    at Object.801 (main.cd634a36.chunk.js:1:53747)
    at u ((index):1:1297)
    at Module.1825 (main.cd634a36.chunk.js:1:29040)
    at u ((index):1:1297)
    at r ((index):1:1166)
    at Array.t [as push] ((index):1:1029)
    at main.cd634a36.chunk.js:1:95
```

**Comment by jakubgs** [comment]
It works fine with `yarn start`:

![image](https://user-images.githubusercontent.com/2212681/167105682-d2b22eca-35c7-4a59-b3ff-3776639f4c31.png)

But fails when I try to host it as a static page from `packages/react-app/build`.

**Comment by jakubgs** [comment]
The `crypto and/or subtle api unavailable` error appears to be the one described here:

* https://github.com/status-im/js-waku/issues/345

But the [suggested solution](https://github.com/status-im/js-waku/issues/345#issuecomment-989622400) by @D4nte is to use HTTPS, but it works fine with `yarn start` without HTTPS.

**Comment by jakubgs** [comment]
And this indeed an error that comes from `js-waku`:
```js
if (subtle === undefined) {
  throw new Error("crypto and/or subtle api unavailable");
}
```
https://github.com/status-im/js-waku/blob/e55177d78d03e1000cfbe2763aca0e2f97762e7e/src/lib/crypto.ts#L21-L23

**Comment by jakubgs** [comment]
Well, I'll follow the HTTPS suggestion and try to get this hosted behind some TLS.

**Comment by D4nte** [comment]
Yes it needs https. It is expected to work locally without https, it's just a modern browser thing

**Comment by jakubgs** [comment]
But why would it work fine with `yarn start` though? That doesn't use HTTPS either.

**Comment by jakubgs** [comment]
Wat, now it works. I'm not sure why but after another rebuild it just works fine now.

**Comment by jakubgs** [comment]
Well isn't this fun:
```
Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.

Failed to compile.
```
Which is great because the build generates a shitload of errors. And the only way is to [pretend we are not in CI](https://stackoverflow.com/questions/62415804/).

**Comment by jakubgs** [comment]
I have no idea why sometimes it works and sometimes it doesn't, but this PR deploys it as a static page and it works:

* https://github.com/status-im/gnosis-safe-waku/pull/2

So I'm closing this for now.
